name: CI

on:
  push:
    branches:
      - master
  pull_request:
env:
  CI: true
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Cache ~/.pnpm-store
        uses: actions/cache@main
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}
      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build --filter ./packages --filter !./packages/create-svelte/templates
      - run: pnpm lint
      - run: pnpm check
  Tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 6
    strategy:
      matrix:
        node-version: [14]
        os: [ubuntu-latest, macOS-latest, windows-latest]
        include:
          - node-version: 12
            os: ubuntu-latest
          - node-version: 15
            os: ubuntu-latest
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get paths for OS
        uses: ./.github/actions/env
        id: paths
      - name: Cache ~/.pnpm-store
        id: cache
        uses: actions/cache@main
        with:
          path: ${{ steps.paths.outputs.pnpm_cache_path }}
          key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}
      - name: Cache browsers
        id: browser_cache
        uses: actions/cache@main
        with:
          path: ${{ steps.paths.outputs.browser_cache_path }}
          key: pw-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: ${{ steps.browser_cache.outputs.cache-hit == 'true' }}
      - run: pnpm build --filter ./packages --filter !./packages/create-svelte/templates
      - run: pnpm test
  Examples:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 6
    strategy:
      matrix:
        node-version: [14]
        os: [ubuntu-latest, macOS-latest, windows-latest]
        include:
          - node-version: 12
            os: ubuntu-latest
          - node-version: 15
            os: ubuntu-latest
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get paths for OS
        uses: ./.github/actions/env
        id: paths
      - name: Cache ~/.pnpm-store
        uses: actions/cache@main
        with:
          path: ${{ steps.paths.outputs.pnpm_cache_path }}
          key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}
      - run: npm install -g pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm build && pnpm build --filter="hn.svelte.dev"
